name: Release workflow

on:
  push:
    tags:
      - "*"

# avoid having multiple CIs running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python "3.13"
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Generate executable
        run: pyinstaller --onefile --icon=assets/icon.ico --name=certificate-generator main.py

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/certificate-generator.exe

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python "3.13"
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Generate executable
        run: pyinstaller --onefile --icon=assets/icon.ico --name=certificate-generator main.py

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/certificate-generator
            config.yml

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
